### ISSUE TITLE
인증 도메인 설계 및 엔티티 추가

### ISSUE THREAD

**Issue by slolee** [zoopi-palette/zoopi-spring-backend#21]
## Feature Description
- 인증 도메인 설계 및 엔티티 추가

## Todo list
- [ ] 헌혈 인증 Entity 개발
- [ ] 헌혈 인증 디테일(지정헌혈) Entity 개발
- [ ] 수혈 인증 Entity 개발
- [ ] 각 Entity 에 필요한 도메인 기능 개발
