### ISSUE TITLE
설정 파일, 응답/예외 클래스 추가

### ISSUE THREAD

**Issue by seonpilKim** [zoopi-palette/zoopi-spring-backend#3]
## Feature Description
- 설정 파일 추가
    - JpaAuditingConfig
    - QuerydslConfig
    - SwaggerConfig
    - 나머지 필요한 설정 파일은 기능 구현 시 추가
- 응답 클래스 추가
    - ErrorCode, ResultCode
    - ErrorResponse, ResultResponse
- 글로벌 예외 클래스 추가
    - EntityNotFoundException
    - InvalidInputException
    - EntityAlreadyExistException
- 글로벌 예외 핸들러 추가
    - GlobalExceptionHandler
    

## Todo list
- [ ] 설정 파일 추가
- [ ] 응답 클래스 추가
- [ ] 글로벌 예외 클래스 추가
- [ ] 글로벌 예외 핸들러 추가
